//! The configuration reference, written from the schema rather than by hand.
//!
//! `config.json` has 238 settable values in it. A reference for them is worth
//! having and is not worth maintaining: a hand-written table of that size is
//! wrong the first time somebody adds a key and does not add a row, and the
//! failure is the quiet one this repository keeps running into — the setting
//! exists, nothing says so, and the only way to find it is to read the Rust.
//!
//! So the table is derived, the same way the settings screen's form is. Types
//! and defaults come from [`crate::settings::fields`] and [`Config::default`],
//! which are the same source the shell itself reads.
//!
//! The prose is the interesting part. Doc comments on the schema are the one
//! place a key is already explained, so rather than restate them somewhere a
//! reader of the schema will never look, this compiles the schema's own source
//! in with `include_str!` and reads them back out. A key documented in
//! `schema.rs` is documented in `docs/config.md` on the next `pnpm gen:docs`,
//! and there is no second copy to fall behind.
//!
//! That makes a source parser part of the build, which would be a bad idea
//! against arbitrary Rust. It is a reasonable one here because `config_struct!`
//! only accepts one shape, so anything that compiles is something this can
//! read — and the tests below hold every path in the schema against the parse,
//! so a change the parser cannot follow fails `cargo test` rather than silently
//! emitting a reference with holes in it.

use std::collections::BTreeMap;

use serde_json::Value;

use crate::settings::FieldKind;
use crate::Config;

/// The schema's own source, compiled in.
///
/// Read at compile time rather than from disk: the reference is generated by an
/// example binary that can be run from anywhere, and a relative path would make
/// that depend on the working directory.
const SCHEMA: &str = include_str!("config/schema.rs");

/// One field as the schema declares it.
struct Declared {
    /// The JSON key — `reserveSpace`, not `reserve_space`.
    key: String,
    /// The declared type, which is how nesting is followed: a name that is
    /// itself a declared struct is a group, and anything else is a leaf.
    type_name: String,
    /// The doc comment, joined into one paragraph.
    doc: String,
}

/// Every `config_struct!` in the schema, by name, with its fields in order.
fn declarations() -> BTreeMap<String, Vec<Declared>> {
    let mut structs: BTreeMap<String, Vec<Declared>> = BTreeMap::new();
    let mut current: Option<String> = None;
    let mut doc: Vec<String> = Vec::new();

    for line in SCHEMA.lines() {
        let trimmed = line.trim();

        // Doc comments accumulate until something claims them. A blank `///`
        // line separates paragraphs in the source; joined here, because the
        // reference renders each note as a single list item.
        if let Some(rest) = trimmed.strip_prefix("///") {
            let text = rest.trim();
            if !text.is_empty() {
                doc.push(text.to_owned());
            }
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("pub struct ") {
            // `config_struct!`'s own definition contains `pub struct $name`
            // twice, once in the pattern and once in the expansion. A real
            // struct's name is a plain identifier, which is what tells the two
            // apart without needing to know where the macro ends.
            current = rest
                .split_whitespace()
                .next()
                .filter(|name| {
                    name.chars()
                        .all(|character| character.is_alphanumeric() || character == '_')
                })
                .map(str::to_owned);
            doc.clear();
            continue;
        }

        // The macro puts each struct's closing brace at one indent, so this
        // ends the body without needing to count braces.
        if trimmed == "}" {
            current = None;
            doc.clear();
            continue;
        }

        let Some(name) = current.clone() else {
            doc.clear();
            continue;
        };

        // Only the part before `=` is read, so a default spanning several lines
        // — `vec![` and its items — needs no special handling.
        let Some(head) = trimmed
            .strip_prefix("pub ")
            .and_then(|rest| rest.split_once(" = "))
            .map(|(head, _)| head)
        else {
            doc.clear();
            continue;
        };
        let Some((field, type_name)) = head.split_once(": ") else {
            doc.clear();
            continue;
        };

        structs.entry(name).or_default().push(Declared {
            key: camel(field.trim().trim_start_matches("r#")),
            type_name: type_name.trim().to_owned(),
            doc: std::mem::take(&mut doc).join(" "),
        });
    }

    structs
}

/// `reserve_space` → `reserveSpace`, matching `#[serde(rename_all)]`.
fn camel(snake: &str) -> String {
    let mut out = String::new();
    let mut upper = false;

    for character in snake.chars() {
        if character == '_' {
            upper = true;
        } else if upper {
            out.extend(character.to_uppercase());
            upper = false;
        } else {
            out.push(character);
        }
    }

    out
}

/// Every documented path, groups included.
///
/// Groups matter as much as leaves here: `background.widgets` is where the
/// sentence explaining what desktop widgets are belongs, and repeating it on
/// each of the seven widgets underneath would be worse than saying it once.
fn descriptions() -> BTreeMap<String, String> {
    let structs = declarations();
    let mut found = BTreeMap::new();
    walk("", "Config", &structs, &mut found);
    found
}

fn walk(
    prefix: &str,
    type_name: &str,
    structs: &BTreeMap<String, Vec<Declared>>,
    into: &mut BTreeMap<String, String>,
) {
    // Not a declared struct, so the path stops here. This is what separates a
    // group from a leaf without the parser needing to know that `bool` and
    // `Vec<String>` are primitives.
    let Some(fields) = structs.get(type_name) else {
        return;
    };

    for field in fields {
        let path = if prefix.is_empty() {
            field.key.clone()
        } else {
            format!("{prefix}.{}", field.key)
        };

        if !field.doc.is_empty() {
            into.insert(path.clone(), field.doc.clone());
        }
        walk(&path, &field.type_name, structs, into);
    }
}

/// What to call each kind of value in the reference.
///
/// Deliberately not the Rust or JSON type name: the reader is editing a file,
/// and "whole number" tells them what may go there in a way `u32` does not.
fn kind_name(kind: FieldKind) -> &'static str {
    match kind {
        FieldKind::Toggle => "true / false",
        FieldKind::Integer => "whole number",
        FieldKind::Decimal => "number",
        FieldKind::Text => "text",
        FieldKind::TextList => "list of text",
        FieldKind::Unsupported => "edit in the file",
    }
}

/// The value at a dotted path in the serialised defaults.
fn at<'a>(root: &'a Value, path: &str) -> Option<&'a Value> {
    let mut node = root;
    for segment in path.split('.') {
        node = node.get(segment)?;
    }
    Some(node)
}

/// A default as it is written in `config.json`.
///
/// Pipes are escaped because these go in a table cell. Nothing in the schema
/// contains one today; a default that did would otherwise split a row into
/// extra columns, which is exactly the sort of silent breakage a generated
/// document should not be able to introduce.
fn render(value: &Value) -> String {
    let text = serde_json::to_string(value).unwrap_or_else(|_| "?".to_owned());
    format!("`{}`", text.replace('|', "\\|"))
}

/// The whole reference.
pub fn markdown() -> String {
    let fields = crate::settings::fields();
    let defaults = serde_json::to_value(Config::default()).expect("the config is serialisable");
    let notes = descriptions();

    let mut out = String::new();
    out.push_str(HEADER);

    if fields
        .iter()
        .any(|field| field.kind == FieldKind::Unsupported)
    {
        out.push_str(UNSUPPORTED_NOTE);
    }
    out.push('\n');

    // Sections in the order the schema declares them, which is the order the
    // settings screen shows them in.
    let mut sections: Vec<&str> = Vec::new();
    for field in &fields {
        if !sections.contains(&field.section.as_str()) {
            sections.push(&field.section);
        }
    }

    out.push_str("## Contents\n\n");
    for section in &sections {
        out.push_str(&format!(
            "- [`{section}`](#{})\n",
            section.to_ascii_lowercase()
        ));
    }

    for section in &sections {
        out.push_str(&format!("\n## `{section}`\n"));
        if let Some(note) = notes.get(*section) {
            out.push_str(&format!("\n{note}\n"));
        }

        // Groups within the section, in the order they first appear. A group is
        // a parent path: unambiguous in a way the parent's *label* is not, since
        // two different parents in one section can share a name.
        let mut groups: Vec<&str> = Vec::new();
        for field in fields.iter().filter(|field| field.section == *section) {
            let parent = parent_of(&field.path);
            if !groups.contains(&parent) {
                groups.push(parent);
            }
        }

        for group in groups {
            if group != *section {
                out.push_str(&format!("\n### `{group}`\n"));
                if let Some(note) = notes.get(group) {
                    out.push_str(&format!("\n{note}\n"));
                }
            }

            let rows: Vec<_> = fields
                .iter()
                .filter(|field| field.section == *section && parent_of(&field.path) == group)
                .collect();

            out.push_str("\n| Setting | Value | Default |\n| --- | --- | --- |\n");
            for field in &rows {
                let default = at(&defaults, &field.path)
                    .map(render)
                    // Unreachable while `fields` and `Config::default` come from
                    // the same value, which a test below holds.
                    .unwrap_or_else(|| "—".to_owned());
                out.push_str(&format!(
                    "| `{}` | {} | {default} |\n",
                    field.path,
                    kind_name(field.kind)
                ));
            }

            // Only the keys that have something to say. A note per row would
            // mean inventing prose for the 134 keys whose name is the whole
            // explanation, and invented prose is worse than none.
            let explained: Vec<_> = rows
                .iter()
                .filter_map(|field| notes.get(&field.path).map(|note| (field, note)))
                .collect();

            if !explained.is_empty() {
                out.push('\n');
                for (field, note) in explained {
                    out.push_str(&format!("- **`{}`** — {note}\n", field.path));
                }
            }
        }
    }

    out
}

/// The path with its last segment removed — `bar.left` → `bar`.
fn parent_of(path: &str) -> &str {
    path.rsplit_once('.').map(|(head, _)| head).unwrap_or(path)
}

const HEADER: &str = r#"<!-- Generated from crates/bw-core/src/config/schema.rs by `pnpm gen:docs`. Do not edit. -->

# Configuration reference

Everything `config.json` accepts, with the value it has when nothing sets it.

The file lives at `%APPDATA%\beautiful-wallpaper\config.json`. It is watched
both ways: an edit in any editor reaches the shell without a restart, and a
change made in the shell is written back. Anything the shell cannot parse is
ignored until the next save, so a half-written file mid-edit is not a problem —
but an unknown key **is** rejected, which is deliberate: a typo that silently
did nothing would look exactly like a setting that does not work.

Three ways to change a value:

- **Settings** — the screen is built from this same schema, so every key here
  has a control there.
- **The CLI** — `bw config set bar.reserveSpace false`, taking the dotted paths
  below verbatim.
- **The file** — any editor.
"#;

/// Explains the one value kind the settings screen cannot draw a control for.
///
/// Emitted only when the schema actually contains one. Today it does not, and a
/// legend for a marker that never appears is the same failure as a table row for
/// a setting that does not exist — it sends somebody looking for something that
/// is not there.
const UNSUPPORTED_NOTE: &str = "
Values marked _edit in the file_ are lists or objects the generated form cannot
draw a control for. They are listed anyway: a setting nobody can see is worse
than one that says where to change it.
";

#[cfg(test)]
mod tests {
    use super::*;

    /// The parser's contract with the schema. If `config_struct!` grows a shape
    /// this cannot read, the reference would quietly lose whole structs — so
    /// the count is held here rather than discovered by someone reading the
    /// generated file.
    #[test]
    fn every_struct_in_the_schema_is_parsed() {
        let structs = declarations();
        // Counted by macro invocation rather than by `pub struct`, so this is
        // an independent measure of the same number: the parser finds struct
        // headers, and there is exactly one struct per `config_struct!`.
        let declared = SCHEMA.matches("config_struct! {").count();

        assert_eq!(
            structs.len(),
            declared,
            "the parser missed a struct the schema declares"
        );
        assert!(structs.contains_key("Config"));
        assert!(structs.contains_key("Bar"));
        // The macro's own definition must not be mistaken for a declaration.
        assert!(structs.keys().all(|name| !name.contains('$')));
    }

    /// The one that matters: every settable path resolves through the parse.
    /// A parser that silently stopped following nesting would still produce a
    /// plausible-looking document, and this is what makes that a test failure.
    #[test]
    fn the_parse_reaches_every_settable_path() {
        let structs = declarations();
        let mut reached: BTreeMap<String, String> = BTreeMap::new();

        fn collect(
            prefix: &str,
            type_name: &str,
            structs: &BTreeMap<String, Vec<Declared>>,
            into: &mut BTreeMap<String, String>,
        ) {
            let Some(fields) = structs.get(type_name) else {
                return;
            };
            for field in fields {
                let path = if prefix.is_empty() {
                    field.key.clone()
                } else {
                    format!("{prefix}.{}", field.key)
                };
                into.insert(path.clone(), field.type_name.clone());
                collect(&path, &field.type_name, structs, into);
            }
        }
        collect("", "Config", &structs, &mut reached);

        for field in crate::settings::fields() {
            assert!(
                reached.contains_key(&field.path),
                "`{}` is settable but the schema parse never reached it",
                field.path
            );
        }
    }

    /// Doc comments are the whole reason the schema is parsed rather than just
    /// walked, so a change that stopped collecting them has to fail loudly.
    #[test]
    fn doc_comments_come_through_attached_to_their_key() {
        let notes = descriptions();

        let rounding = notes
            .get("appearance.fakeScreenRounding")
            .expect("that key is documented in the schema");
        assert!(
            rounding.contains("full-screen"),
            "got: {rounding}",
            rounding = rounding
        );

        // Paragraphs are joined, not truncated to the first one.
        assert!(rounding.len() > 120, "the whole comment should be here");
    }

    /// Every section needs a sentence saying what it is for. This is the only
    /// prose the reference cannot derive from a key name, and a new section
    /// without one would print a bare heading over a table.
    #[test]
    fn every_section_says_what_it_is_for() {
        let notes = descriptions();
        let value = serde_json::to_value(Config::default()).expect("serialisable");

        for section in value.as_object().expect("an object").keys() {
            let note = notes.get(section).unwrap_or_else(|| {
                panic!("`{section}` has no doc comment in `Config`; the reference needs one")
            });
            assert!(
                note.len() > 20,
                "`{section}`'s description is too short to be useful: {note}"
            );
        }
    }

    #[test]
    fn a_key_appears_with_its_type_and_its_default() {
        let out = markdown();

        assert!(out.contains("| `bar.reserveSpace` | true / false | `true` |"));
        assert!(out.contains("| `bar.height` | whole number | `40` |"));
        assert!(out.contains("| `appearance.roundingScale` | number | `1.0` |"));
    }

    /// Groups are keyed by parent path rather than by the parent's label, so
    /// two different parents that happen to share a name stay apart.
    #[test]
    fn nested_groups_get_their_own_heading() {
        let out = markdown();

        assert!(out.contains("## `background`"));
        assert!(out.contains("### `background.widgets.clock`"));
        // The section's own keys sit under the section heading, with no
        // group heading repeating the section name.
        assert!(!out.contains("### `background`\n"));
    }

    #[test]
    fn the_contents_link_to_every_section() {
        let out = markdown();
        let value = serde_json::to_value(Config::default()).expect("serialisable");

        for section in value.as_object().expect("an object").keys() {
            assert!(
                out.contains(&format!(
                    "- [`{section}`](#{})",
                    section.to_ascii_lowercase()
                )),
                "`{section}` is missing from the contents"
            );
        }
    }

    /// Every row's default has to come from somewhere; an em dash in the
    /// generated file would mean `fields` and `Config::default` had drifted.
    #[test]
    fn no_row_is_missing_its_default() {
        assert!(
            !markdown().contains("| — |"),
            "a settable path had no value in the defaults"
        );
    }

    /// The legend and the thing it explains have to appear together. Today no
    /// key is unsupported, so neither should be there; adding one that is must
    /// bring the paragraph back rather than leave an unexplained marker.
    #[test]
    fn the_legend_appears_exactly_when_something_needs_it() {
        let out = markdown();
        let needed = crate::settings::fields()
            .iter()
            .any(|field| field.kind == FieldKind::Unsupported);

        assert_eq!(
            out.contains("Values marked _edit in the file_"),
            needed,
            "the legend and the rows it explains disagree"
        );
        assert_eq!(out.contains("| edit in the file |"), needed);
    }

    #[test]
    fn keys_are_camel_case_like_the_json() {
        assert_eq!(camel("reserve_space"), "reserveSpace");
        assert_eq!(camel("enable"), "enable");
        assert_eq!(camel("sync_windows_terminal"), "syncWindowsTerminal");
    }
}
