// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fonts } from "./Fonts";
import type { Palette } from "./Palette";
import type { Transparency } from "./Transparency";
import type { WallpaperTheming } from "./WallpaperTheming";

export type Appearance = { 
/**
 * `"auto"` picks a scheme variant per wallpaper, otherwise a fixed
 * Material variant name (`tonalSpot`, `neutral`, `vibrant`, ...).
 */
palette: Palette, fonts: Fonts, 
/**
 * Extra translucency applied on top of the wallpaper-derived value.
 */
transparency: Transparency, wallpaperTheming: WallpaperTheming, 
/**
 * Corner rounding multiplier applied to every surface.
 */
roundingScale: number, };
