// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetPlacement } from "./WidgetPlacement";

export type DesktopWidgets = { enable: boolean, 
/**
 * Snap-to-grid step, in pixels, for dragged widgets.
 */
grid: number, clock: WidgetPlacement, media: WidgetPlacement, weather: WidgetPlacement, resources: WidgetPlacement, calendar: WidgetPlacement, userCard: WidgetPlacement, notes: WidgetPlacement, };
