// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the wallpaper browser — a folder to descend into, or an image.
 */
export type Entry = { path: string, name: string, isDirectory: boolean, };
