// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Fonts = { main: string, title: string, monospace: string, reading: string, expressive: string, pixelSize: number, };
