// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Light or dark, already resolved — `"auto"` is decided before we get here.
 */
export type Mode = "light" | "dark";
