// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnlineWallpapers = { enable: boolean, 
/**
 * `"wallhaven"` | `"unsplash"` | `"pexels"`
 */
defaultProvider: string, 
/**
 * `"1080p"` | `"2k"` | `"4k"`
 */
resolution: string, 
/**
 * Wallhaven purity filter: `"sfw"` | `"sketchy"` | `"nsfw"`.
 */
purity: string, category: string, 
/**
 * Where downloads land; empty means `%USERPROFILE%\Pictures\Wallpapers`.
 */
downloadPath: string, };
