// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Palette = { 
/**
 * `"auto"` | `"tonalSpot"` | `"neutral"` | `"vibrant"` | `"expressive"`
 * | `"content"` | `"fidelity"` | `"monochrome"` | `"rainbow"`
 * | `"fruitSalad"`
 */
type: string, 
/**
 * When set, overrides the colour extracted from the wallpaper.
 */
accentColor: string | null, 
/**
 * `"auto"` follows the wallpaper's luminance, else `"light"` / `"dark"`.
 */
mode: string, };
