// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Policies = { 
/**
 * 0 = off, 1 = on, 2 = local only.
 */
ai: number, weeb: number, };
