// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

/**
 * What to ask a provider for.
 */
export type Query = { provider: Provider, search: string, page: number, 
/**
 * `"1080p"` | `"2k"` | `"4k"`
 */
resolution: string, 
/**
 * Wallhaven only: `"sfw"` | `"sketchy"` | `"nsfw"`.
 */
purity: string, category: string, 
/**
 * Keeps "random" ordering stable while paging through it.
 */
seed: string, };
