// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Resources = { 
/**
 * Sampling interval for CPU/RAM/disk, in milliseconds.
 */
pollInterval: number, showSwap: boolean, };
