// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transparency = { enable: boolean, 
/**
 * Added to the wallpaper-derived background transparency.
 */
extra: number, };
