// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallpaperItem } from "./WallpaperItem";

/**
 * A page of results.
 */
export type WallpaperPage = { items: Array<WallpaperItem>, page: number, totalPages: number, };
