// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnlineWallpapers } from "./OnlineWallpapers";

export type WallpaperSelector = { userPath: string, columns: number, showSearchbar: boolean, closeAfterSelection: boolean, 
/**
 * Seconds between automatic wallpaper rotations; 0 disables it.
 */
changeInterval: number, extensions: Array<string>, online: OnlineWallpapers, };
