// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Position and visibility of one desktop widget.
 */
export type WidgetPlacement = { id: string, enable: boolean, 
/**
 * Fraction of the monitor's width, so placement survives resolution changes.
 */
x: number, y: number, 
/**
 * `"free"` keeps the stored position; `"leastBusy"` moves the widget to
 * the calmest region of the current wallpaper.
 */
placementStrategy: string, style: string, };
