// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkSafety = { 
/**
 * Replace the wallpaper with a flat colour when its filename matches
 * one of the keywords below.
 */
blankWallpaper: boolean, keywords: Array<string>, };
